### ISSUE TITLE
Putting host and port in common config settings

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#1020]
Currently, the config file lets the user define for the searcher and for the indexer the `rest_listen_address` and `rest_listen_port`. Moreover, we define implicitly the grpc service on `rest_listen_port` + 1 for the searcher. 

What I have in mind for Quickwit is something like this:
- if a user wants to start several services like searcher + indexer on the same machine, I would want to define once for all `rest_listen_address` and `rest_listen_port`. Grpc service is on `rest_listen_port` + 1 by default. I would not want different ports.
- if a user wants to start a single service like the searcher one, having a common `rest_listen_address` and `rest_listen_port` is fine too. 
- there is the special case of UI. In general, people expects a front and a back and I like this separation, so I would have a specific port for the UI.

There is also the gossip configuration that is currently linked to `rest_listen_address` and `rest_listen_port` defined for the searcher. But the gossip protocol will be used for every quickwit instance service (searcher, indexer, metastore server) and consequently we should detach its configuration from the searcher config.

Finally, I would target a config file like this:

```yaml
server_config:
  listen_address: 127.0.0.1
  rest_listen_port: 7280
  grpc_listen_port: 7281

gossip_swim:
  node_id: searcher-1
  listen_address: 7280
  peers: 
     - 172.1.0.12
     - 172.1.0.13

```

What do you think?

You can have a look at Loki config spec: https://grafana.com/docs/loki/latest/configuration/#server_config

**Comment by fulmicoton** [comment]
Discuss live:
Francois's idea is to let the user start several services on the same process and have them share the same http rest server.

**Comment by fmassot** [comment]
After discussions, here is the config file for the 0.2:

```yaml
node_id: searcher-1
listen_address: 127.0.0.1
rest_listen_port: 7280
seeds:
   - 172.1.0.12
   - 172.1.0.13
```
